# Generated by Django 3.0.4 on 2020-04-09 01:31

import annoying.fields
from django.conf import settings
import django.db.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields
import inbox.constants
import inbox.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('subject', models.TextField(blank=True, db_index=True, null=True)),
                ('body', models.TextField(blank=True, db_index=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('data', django.db.models.JSONField(blank=True, db_index=True, help_text='Arbitrary data that can be used by consuming  clients/signal listeners as needed (eg needing extra data to pass with Gmail emails for actions, extra data for push notifications for interactive notifications.', null=True)),
                ('message_id', models.CharField(db_index=True, default=inbox.models.default_message_id, help_text='Explicitly specifying a message id enables message de-duplication per user.', max_length=255)),
                ('group', models.CharField(db_index=True, default='default', max_length=255, validators=[inbox.models.validate_group])),
                ('is_hidden', models.BooleanField(default=False, help_text="There may be cases you want to generate a message so that it can trigger communication in other channels but you don't want it to show up in the user's inbox, set this flag to true.")),
                ('send_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Marked Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-send_at',),
            },
        ),
        migrations.CreateModel(
            name='MessagePreferences',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='message_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('_groups', inbox.models.JSONSchemaField(blank=True, db_column='groups', db_index=True, default=inbox.models.get_default_preferences, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', django_enumfield.db.fields.EnumField(enum=inbox.constants.MessageMedium)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=inbox.constants.MessageLogStatus)),
                ('failure_reason', django_enumfield.db.fields.EnumField(default=None, enum=inbox.constants.MessageLogFailureReason, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.Message')),
            ],
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['-send_at', 'status'], name='inbox_messa_send_at_93affd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-send_at', 'is_hidden', 'deleted_at'], name='inbox_messa_send_at_c1925c_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('user', 'message_id'), name='unique_user_message_id'),
        ),
    ]
