# Generated by Django 2.2.2 on 2020-04-14 16:39

import django.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='link',
        ),
        migrations.AddField(
            model_name='message',
            name='data_email',
            field=django.db.models.JSONField(blank=True, db_index=True, help_text='Arbitrary data that is included with data when creating email templates.', null=True),
        ),
    ]
