# Generated by Django 2.2.2 on 2020-04-14 16:39

from django.db import migrations
import django.db.models

if django.VERSION >= (3, 1):
    from django.db.models import JSONField
else:
    from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='link',
        ),
        migrations.AddField(
            model_name='message',
            name='data_email',
            field=JSONField(blank=True, db_index=True, help_text='Arbitrary data that is included with data when creating email templates.', null=True),
        ),
    ]
