# Generated by Django 2.2.2 on 2020-04-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_auto_20200414_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inbox.Message'),
        ),
    ]
