# Generated by Django 2.2.2 on 2020-04-20 16:42

from django.db import migrations
import django_enumfield.db.fields
import inbox.constants


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_auto_20200414_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=1, enum=inbox.constants.MessageLogStatus),
        ),
    ]
