# Generated by Django 3.0.6 on 2020-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_auto_20200420_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
