# Generated by Django 3.0.6 on 2020-05-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_message_is_logged'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='inbox_messa_send_at_c1925c_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='group',
            new_name='group_id',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-send_at', 'read_at', 'deleted_at', 'is_hidden'], name='inbox_messa_send_at_f3895a_idx'),
        ),
    ]
