# Generated by Django 3.0.6 on 2020-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_auto_20200506_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
