# Generated by Django 3.0.10 on 2020-10-14 11:45

from django.db import migrations, models


def clear_message_id_uuid4(apps, schema_editor):
    """
    Default value for message_id on Message was uuid4, now making it null that way we know for sure any case where
    message_id wasn't explicitly set.
    """
    Message = apps.get_model('inbox', 'Message')
    message_id_regex = r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    Message.objects.filter(message_id__iregex=message_id_regex).update(message_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_message_is_forced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Explicitly specifying a message id enables message de-duplication per user.', max_length=255, null=True),
        ),
        migrations.RunPython(clear_message_id_uuid4)
    ]
