# Generated by Django 3.0.10 on 2020-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0009_message_id_default_clear_prev_uuid4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
