# Generated by Django 3.0.10 on 2021-03-24 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('inbox', '0010_auto_20201129_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunSQL('CREATE INDEX CONCURRENTLY inbox_message_send_at '
                          'ON inbox_message (send_at) WHERE is_logged = FALSE;'),
        migrations.RunSQL('CREATE INDEX CONCURRENTLY inbox_message_user_send_at_desc '
                          'ON inbox_message (user_id, send_at DESC);'),
    ]
