# Generated by Django 3.1.12 on 2022-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0012_auto_20210827_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated'),
        ),
    ]
