# Generated by Django 3.1.12 on 2022-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('inbox', '0014_auto_20220610_1541'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY inbox_messa_send_at_deee9f_idx "
            "ON inbox_messagelog (send_at, status);",
            state_operations=[
                migrations.AddIndex(
                    model_name='messagelog',
                    index=models.Index(fields=['send_at', 'status'], name='inbox_messa_send_at_bf95f9_idx'),
                ),
            ],
        )
    ]
