# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - sudo apt-get update
          - sudo apt-get install build-essential software-properties-common -y
          - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          - sudo apt-get update
          - sudo apt-get install gcc-snapshot -y
          - sudo apt-get update
          - sudo apt-get install gcc-6 g++-6 -y
          - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
          - sudo apt-get install gcc-4.8 g++-4.8 -y
          - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
          - sudo update-alternatives --config gcc
          - pip install .
          - python setup.py test
        services: 
          - postgres

definitions: 
  services: 
    postgres: 
      image: postgres 
      variables: 
        POSTGRES_DB: inbox 
        POSTGRES_USER: inbox 
        POSTGRES_PASSWORD: password