services:
  db:
    container_name: django-inbox-db
    image: postgres:15
    user: postgres
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: inbox
      POSTGRES_USER: inbox
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inbox"]
      interval: 10s
      timeout: 5s
      retries: 5
  inbox:
    &inbox
    container_name: django-inbox
    image: python:3.9
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  inbox-django-2.2:
    <<: *inbox
    container_name: django-inbox-django-2.2
    environment:
      - DJANGO_VERSION=2.2,<3.0
    entrypoint: /app/entrypoint.sh
  inbox-django-3:
    <<: *inbox
    container_name: django-inbox-django-3
    environment:
      - DJANGO_VERSION=3.0,<4.0
    entrypoint: /app/entrypoint.sh
  inbox-django-4:
    <<: *inbox
    container_name: django-inbox-django-4
    environment:
      - DJANGO_VERSION=4.0,<5.0
    entrypoint: /app/entrypoint.sh
  inbox-django-5:
    <<: *inbox
    image: python:3.10
    container_name: django-inbox-django-5
    environment:
      - DJANGO_VERSION=5.0,<6.0
    entrypoint: /app/entrypoint.sh
